import Head from "next/head";
import Image from "next/image";
import Featured from "../components/Featured";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <Hero />
            <main className="max-w-lg lg:max-w-[1440px] w-10/12 lg:w-11/12 mx-auto my-10 font-open-sans">
                <Featured />
            </main>
            <Footer />
        </>
    );
}
